# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit configuration — only non-default values shown.
# Full schema: https://coderabbit.ai/integrations/schema.v2.json
early_access: true
reviews:
  request_changes_workflow: true
  review_details: true
  fail_commit_status: true
  auto_apply_labels: true
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
  auto_review:
    auto_pause_after_reviewed_commits: 0
issue_enrichment:
  auto_enrich:
    enabled: true
